const savedInfo = [
  {
    id: 1,
    image: "https://cdn2.thedogapi.com/images/BJa4kxc4X_1280.jpg",
    name: "Affenpinscher",
    weight: "3 - 6",
    height: "23 - 29",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
  },
  {
    id: 2,
    image: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    name: "Afghan Hound",
    weight: "23 - 27",
    height: "64 - 69",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
  },
  {
    id: 3,
    image: "https://cdn2.thedogapi.com/images/rkiByec47_1280.jpg",
    name: "African Hunting Dog",
    weight: "20 - 30",
    height: "76",
    life_span: "11 years",
    belongToDb: false,
    temperament: "Wild, Hardworking, Dutiful",
  },
  {
    id: 4,
    image: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    name: "Airedale Terrier",
    weight: "18 - 29",
    height: "53 - 58",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
  },
  {
    id: 5,
    image: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    name: "Akbash Dog",
    weight: "41 - 54",
    height: "71 - 86",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Loyal, Independent, Intelligent, Brave",
  },
  {
    id: 6,
    image: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    name: "Akita",
    weight: "29 - 52",
    height: "61 - 71",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament:
      "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
  },
  {
    id: 7,
    image: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    name: "Alapaha Blue Blood Bulldog",
    weight: "25 - 41",
    height: "46 - 61",
    life_span: "12 - 13 years",
    belongToDb: false,
    temperament: "Loving, Protective, Trainable, Dutiful, Responsible",
  },
  {
    id: 8,
    image: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    name: "Alaskan Husky",
    weight: "17 - 23",
    height: "58 - 66",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament: "Friendly, Energetic, Loyal, Gentle, Confident",
  },
  {
    id: 9,
    image: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    name: "Alaskan Malamute",
    weight: "29 - 45",
    height: "58 - 64",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
  },
  {
    id: 10,
    image: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    name: "American Bulldog",
    weight: "27 - 54",
    height: "56 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
  },
  {
    id: 11,
    image: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    name: "American Bully",
    weight: "14 - 68",
    height: "36 - 43",
    life_span: "8 – 15 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
  },
  {
    id: 12,
    image: "https://cdn2.thedogapi.com/images/Bymjyec4m_1280.jpg",
    name: "American Eskimo Dog",
    weight: "9 - 18",
    height: "38 - 48",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
  },
  {
    id: 13,
    image: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    name: "American Eskimo Dog (Miniature)",
    weight: "3 - 5",
    height: "23 - 30",
    life_span: "13 – 15 years",
    belongToDb: false,
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
  },
  {
    id: 14,
    image: "https://cdn2.thedogapi.com/images/S14n1x9NQ_1280.jpg",
    name: "American Foxhound",
    weight: "29 - 34",
    height: "53 - 71",
    life_span: "8 - 15 years",
    belongToDb: false,
    temperament:
      "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
  },
  {
    id: 15,
    image: "https://cdn2.thedogapi.com/images/HkC31gcNm_1280.png",
    name: "American Pit Bull Terrier",
    weight: "14 - 27",
    height: "43 - 53",
    life_span: "10 - 15 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
  },
  {
    id: 16,
    image: "https://cdn2.thedogapi.com/images/rJIakgc4m_1280.jpg",
    name: "American Staffordshire Terrier",
    weight: "23 - 27",
    height: "43 - 48",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
  },
  {
    id: 17,
    image: "https://cdn2.thedogapi.com/images/SkmRJl9VQ_1280.jpg",
    name: "American Water Spaniel",
    weight: "11 - 20",
    height: "38 - 46",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
  },
  {
    id: 18,
    image: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm_1280.jpg",
    name: "Anatolian Shepherd Dog",
    weight: "36 - 68",
    height: "69 - 74",
    life_span: "11 - 13 years",
    belongToDb: false,
    temperament: "Steady, Bold, Independent, Confident, Intelligent, Proud",
  },
  {
    id: 19,
    image: "https://cdn2.thedogapi.com/images/HkNkxlqEX_1280.jpg",
    name: "Appenzeller Sennenhund",
    weight: "22 - 25",
    height: "51 - 56",
    life_span: "12 – 14 years",
    belongToDb: false,
    temperament: "Reliable, Fearless, Energetic, Lively, Self-assured",
  },
  {
    id: 21,
    image: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    name: "Australian Cattle Dog",
    weight: "20 - 28",
    height: "43 - 51",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
  },
  {
    id: 22,
    image: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ_1280.jpg",
    name: "Australian Kelpie",
    weight: "14 - 21",
    height: "43 - 51",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
  },
  {
    id: 23,
    image: "https://cdn2.thedogapi.com/images/B1-llgq4m_1280.jpg",
    name: "Australian Shepherd",
    weight: "16 - 29",
    height: "46 - 58",
    life_span: "12 - 16 years",
    belongToDb: false,
    temperament: "Good-natured, Affectionate, Intelligent, Active, Protective",
  },
  {
    id: 24,
    image: "https://cdn2.thedogapi.com/images/r1Ylge5Vm_1280.jpg",
    name: "Australian Terrier",
    weight: "6 - 7",
    height: "25 - 28",
    life_span: "15 years",
    belongToDb: false,
    temperament:
      "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
  },
  {
    id: 25,
    image: "https://cdn2.thedogapi.com/images/SkvZgx94m_1280.jpg",
    name: "Azawakh",
    weight: "15 - 25",
    height: "58 - 74",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament: "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
  },
  {
    id: 26,
    image: "https://cdn2.thedogapi.com/images/HyWGexcVQ_1280.jpg",
    name: "Barbet",
    weight: "18 - 29",
    height: "51 - 66",
    life_span: "13 – 15 years",
    belongToDb: false,
    temperament: "Obedient, Companionable, Intelligent, Joyful",
  },
  {
    id: 28,
    image: "https://cdn2.thedogapi.com/images/H1dGlxqNQ_1280.jpg",
    name: "Basenji",
    weight: "10 - 11",
    height: "41 - 43",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
  },
  {
    id: 29,
    image: "https://cdn2.thedogapi.com/images/BkMQll94X_1280.jpg",
    name: "Basset Bleu de Gascogne",
    weight: "16 - 18",
    height: "33 - 38",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament: "Affectionate, Lively, Agile, Curious, Happy, Active",
  },
  {
    id: 30,
    image: "https://cdn2.thedogapi.com/images/Sy57xx9EX_1280.jpg",
    name: "Basset Hound",
    weight: "23 - 29",
    height: "36",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
  },
  {
    id: 31,
    image: "https://cdn2.thedogapi.com/images/Syd4xxqEm_1280.jpg",
    name: "Beagle",
    weight: "9 - 16",
    height: "33 - 38",
    life_span: "13 - 16 years",
    belongToDb: false,
    temperament:
      "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
  },
  {
    id: 32,
    image: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    name: "Bearded Collie",
    weight: "20 - 25",
    height: "51 - 56",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
  },
  {
    id: 33,
    image: "https://cdn2.thedogapi.com/images/HJQ8ge5V7_1280.jpg",
    name: "Beauceron",
    weight: "36 - 50",
    height: "61 - 70",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Fearless, Friendly, Intelligent, Protective, Calm",
  },
  {
    id: 34,
    image: "https://cdn2.thedogapi.com/images/ByK8gx947_1280.jpg",
    name: "Bedlington Terrier",
    weight: "8 - 10",
    height: "38 - 41",
    life_span: "14 - 16 years",
    belongToDb: false,
    temperament: "Affectionate, Spirited, Intelligent, Good-tempered",
  },
  {
    id: 36,
    image: "https://cdn2.thedogapi.com/images/r1f_ll5VX_1280.jpg",
    name: "Belgian Malinois",
    weight: "18 - 36",
    height: "56 - 66",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
  },
  {
    id: 38,
    image: "https://cdn2.thedogapi.com/images/B1KdxlcNX_1280.jpg",
    name: "Belgian Tervuren",
    weight: "18 - 29",
    height: "56 - 66",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
  },
  {
    id: 41,
    image: "https://cdn2.thedogapi.com/images/S1fFlx5Em_1280.jpg",
    name: "Bernese Mountain Dog",
    weight: "29 - 54",
    height: "58 - 70",
    life_span: "7 - 10 years",
    belongToDb: false,
    temperament: "Affectionate, Loyal, Intelligent, Faithful",
  },
  {
    id: 42,
    image: "https://cdn2.thedogapi.com/images/HkuYlxqEQ_1280.jpg",
    name: "Bichon Frise",
    weight: "5 - 8",
    height: "24 - 29",
    life_span: "15 years",
    belongToDb: false,
    temperament: "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
  },
  {
    id: 43,
    image: "https://cdn2.thedogapi.com/images/HJAFgxcNQ_1280.jpg",
    name: "Black and Tan Coonhound",
    weight: "29 - 45",
    height: "58 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
  },
  {
    id: 45,
    image: "https://cdn2.thedogapi.com/images/Skdcgx9VX_1280.jpg",
    name: "Bloodhound",
    weight: "36 - 50",
    height: "58 - 69",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament: "Stubborn, Affectionate, Gentle, Even Tempered",
  },
  {
    id: 47,
    image: "https://cdn2.thedogapi.com/images/rJxieg9VQ_1280.jpg",
    name: "Bluetick Coonhound",
    weight: "20 - 36",
    height: "53 - 69",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Friendly, Intelligent, Active",
  },
  {
    id: 48,
    image: "https://cdn2.thedogapi.com/images/HyOjge5Vm_1280.jpg",
    name: "Boerboel",
    weight: "50 - 91",
    height: "56 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Obedient, Confident, Intelligent, Dominant, Territorial",
  },
  {
    id: 50,
    image: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    name: "Border Collie",
    weight: "14 - 20",
    height: "46 - 56",
    life_span: "12 - 16 years",
    belongToDb: false,
    temperament: "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
  },
  {
    id: 51,
    image: "https://cdn2.thedogapi.com/images/HJOpge9Em_1280.jpg",
    name: "Border Terrier",
    weight: "5 - 7",
    height: "28 - 41",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
  },
  {
    id: 53,
    image: "https://cdn2.thedogapi.com/images/rkZRggqVX_1280.jpg",
    name: "Boston Terrier",
    weight: "5 - 11",
    height: "41 - 43",
    life_span: "11 - 13 years",
    belongToDb: false,
    temperament: "Friendly, Lively, Intelligent",
  },
  {
    id: 54,
    image: "https://cdn2.thedogapi.com/images/Byd0xl5VX_1280.jpg",
    name: "Bouvier des Flandres",
    weight: "32 - 50",
    height: "60 - 70",
    life_span: "10 - 15 years",
    belongToDb: false,
    temperament: "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
  },
  {
    id: 55,
    image: "https://cdn2.thedogapi.com/images/ry1kWe5VQ_1280.jpg",
    name: "Boxer",
    weight: "23 - 32",
    height: "55 - 64",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament:
      "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
  },
  {
    id: 56,
    image: "https://cdn2.thedogapi.com/images/ryHJZlcNX_1280.jpg",
    name: "Boykin Spaniel",
    weight: "11 - 18",
    height: "36 - 46",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament:
      "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
  },
  {
    id: 57,
    image: "https://cdn2.thedogapi.com/images/S13yZg5VQ_1280.jpg",
    name: "Bracco Italiano",
    weight: "25 - 40",
    height: "55 - 67",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
  },
  {
    id: 58,
    image: "https://cdn2.thedogapi.com/images/rkVlblcEQ_1280.jpg",
    name: "Briard",
    weight: "32 - 41",
    height: "56 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
  },
  {
    id: 59,
    image: "https://cdn2.thedogapi.com/images/HJWZZxc4X_1280.jpg",
    name: "Brittany",
    weight: "14 - 20",
    height: "44 - 52",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
  },
  {
    id: 61,
    image: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    name: "Bull Terrier",
    weight: "23 - 32",
    height: "53 - 56",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Trainable, Protective, Sweet-Tempered, Keen, Active",
  },
  {
    id: 62,
    image: "https://cdn2.thedogapi.com/images/BkKZWlcVX_1280.jpg",
    name: "Bull Terrier (Miniature)",
    weight: "11 - 15",
    height: "25 - 36",
    life_span: "11 – 14 years",
    belongToDb: false,
    temperament:
      "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
  },
  {
    id: 64,
    image: "https://cdn2.thedogapi.com/images/r1ifZl5E7_1280.jpg",
    name: "Bullmastiff",
    weight: "45 - 59",
    height: "61 - 69",
    life_span: "8 - 12 years",
    belongToDb: false,
    temperament:
      "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
  },
  {
    id: 65,
    image: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7_1280.jpg",
    name: "Cairn Terrier",
    weight: "6 - 6",
    height: "23 - 25",
    life_span: "14 - 15 years",
    belongToDb: false,
    temperament: "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
  },
  {
    id: 67,
    image: "https://cdn2.thedogapi.com/images/r15m-lc4m_1280.jpg",
    name: "Cane Corso",
    weight: "40 - 54",
    height: "60 - 70",
    life_span: "10 - 11 years",
    belongToDb: false,
    temperament: "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
  },
  {
    id: 68,
    image: "https://cdn2.thedogapi.com/images/SyXN-e9NX_1280.jpg",
    name: "Cardigan Welsh Corgi",
    weight: "11 - 17",
    height: "27 - 32",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
  },
  {
    id: 69,
    image: "https://cdn2.thedogapi.com/images/BJcNbec4X_1280.jpg",
    name: "Catahoula Leopard Dog",
    weight: "23 - 43",
    height: "51 - 66",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
  },
  {
    id: 70,
    image: "https://cdn2.thedogapi.com/images/r1rrWe5Em_1280.jpg",
    name: "Caucasian Shepherd (Ovcharka)",
    weight: "36 - 45",
    height: "61 - 85",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Alert, Quick, Dominant, Powerful, Calm, Strong",
  },
  {
    id: 71,
    image: "https://cdn2.thedogapi.com/images/HJRBbe94Q_1280.jpg",
    name: "Cavalier King Charles Spaniel",
    weight: "6 - 8",
    height: "30 - 33",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament:
      "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
  },
  {
    id: 76,
    image: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    name: "Chesapeake Bay Retriever",
    weight: "25 - 36",
    height: "53 - 66",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
  },
  {
    id: 78,
    image: "https://cdn2.thedogapi.com/images/B1pDZx9Nm_1280.jpg",
    name: "Chinese Crested",
    weight: "5 - 6",
    height: "28 - 33",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament: "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
  },
  {
    id: 79,
    image: "https://cdn2.thedogapi.com/images/B1ruWl94Q_1280.jpg",
    name: "Chinese Shar-Pei",
    weight: "20 - 27",
    height: "46 - 51",
    life_span: "10 years",
    belongToDb: false,
    temperament:
      "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
  },
  {
    id: 80,
    image: "https://cdn2.thedogapi.com/images/Sypubg54Q_1280.jpg",
    name: "Chinook",
    weight: "23 - 41",
    height: "56 - 66",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Alert, Dignified, Intelligent, Calm",
  },
  {
    id: 81,
    image: "https://cdn2.thedogapi.com/images/ry8KWgqEQ_1280.jpg",
    name: "Chow Chow",
    weight: "18 - 32",
    height: "43 - 51",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Aloof, Loyal, Independent, Quiet",
  },
  {
    id: 84,
    image: "https://cdn2.thedogapi.com/images/rkeqWgq4Q_1280.jpg",
    name: "Clumber Spaniel",
    weight: "25 - 39",
    height: "43 - 51",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
  },
  {
    id: 86,
    image: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    name: "Cocker Spaniel",
    weight: "9 - 14",
    height: "36 - 38",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
  },
  {
    id: 87,
    image: "https://cdn2.thedogapi.com/images/HkRcZe547_1280.jpg",
    name: "Cocker Spaniel (American)",
    weight: "9 - 14",
    height: "36 - 38",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
  },
  {
    id: 89,
    image: "https://cdn2.thedogapi.com/images/SyviZlqNm_1280.jpg",
    name: "Coton de Tulear",
    weight: "4 - 7",
    height: "23 - 28",
    life_span: "13 - 16 years",
    belongToDb: false,
    temperament: "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
  },
  {
    id: 92,
    image: "https://cdn2.thedogapi.com/images/SkJ3blcN7_1280.jpg",
    name: "Dalmatian",
    weight: "23 - 25",
    height: "48 - 58",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
  },
  {
    id: 94,
    image: "https://cdn2.thedogapi.com/images/HyL3bl94Q_1280.jpg",
    name: "Doberman Pinscher",
    weight: "30 - 40",
    height: "61 - 71",
    life_span: "10 years",
    belongToDb: false,
    temperament:
      "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
  },
  {
    id: 95,
    image: "https://cdn2.thedogapi.com/images/S1nhWx94Q_1280.jpg",
    name: "Dogo Argentino",
    weight: "36 - 45",
    height: "60 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
  },
  {
    id: 98,
    image: "https://cdn2.thedogapi.com/images/BkE6Wg5E7_1280.jpg",
    name: "Dutch Shepherd",
    weight: "23 - 32",
    height: "56 - 62",
    life_span: "15 years",
    belongToDb: false,
    temperament: "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
  },
  {
    id: 101,
    image: "https://cdn2.thedogapi.com/images/By4A-eqVX_1280.jpg",
    name: "English Setter",
    weight: "20 - 36",
    height: "61 - 64",
    life_span: "12 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
  },
  {
    id: 102,
    image: "https://cdn2.thedogapi.com/images/H1QyMe5EQ_1280.jpg",
    name: "English Shepherd",
    weight: "20 - 30",
    height: "46 - 58",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament: "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
  },
  {
    id: 103,
    image: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ_1280.jpg",
    name: "English Springer Spaniel",
    weight: "16 - 23",
    height: "48 - 51",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
  },
  {
    id: 104,
    image: "https://cdn2.thedogapi.com/images/SkIgzxqNQ_1280.jpg",
    name: "English Toy Spaniel",
    weight: "4 - 6",
    height: "25",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
  },
  {
    id: 105,
    image: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ_1280.jpg",
    name: "English Toy Terrier",
    weight: "3 - 4",
    height: "25 - 30",
    life_span: "12 - 13 years",
    belongToDb: false,
    temperament:
      "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
  },
  {
    id: 107,
    image: "https://cdn2.thedogapi.com/images/S1VWGx9Nm_1280.jpg",
    name: "Eurasier",
    weight: "18 - 32",
    height: "52 - 60",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
  },
  {
    id: 108,
    image: "https://cdn2.thedogapi.com/images/SkJfGecE7_1280.jpg",
    name: "Field Spaniel",
    weight: "16 - 23",
    height: "43 - 46",
    life_span: "11 - 15 years",
    belongToDb: false,
    temperament: "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
  },
  {
    id: 110,
    image: "https://cdn2.thedogapi.com/images/S1KMGg5Vm_1280.jpg",
    name: "Finnish Lapphund",
    weight: "15 - 24",
    height: "41 - 53",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Keen, Faithful, Calm, Courageous",
  },
  {
    id: 111,
    image: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    name: "Finnish Spitz",
    weight: "10 - 13",
    height: "39 - 51",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
  },
  {
    id: 113,
    image: "https://cdn2.thedogapi.com/images/HyWNfxc47_1280.jpg",
    name: "French Bulldog",
    weight: "13",
    height: "28 - 30",
    life_span: "9 - 11 years",
    belongToDb: false,
    temperament:
      "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
  },
  {
    id: 114,
    image: "https://cdn2.thedogapi.com/images/B1u4zgqE7_1280.jpg",
    name: "German Pinscher",
    weight: "11 - 20",
    height: "43 - 51",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
  },
  {
    id: 115,
    image: "https://cdn2.thedogapi.com/images/SJyBfg5NX_1280.jpg",
    name: "German Shepherd Dog",
    weight: "23 - 41",
    height: "56 - 66",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
  },
  {
    id: 116,
    image: "https://cdn2.thedogapi.com/images/SJqBMg5Nm_1280.jpg",
    name: "German Shorthaired Pointer",
    weight: "20 - 32",
    height: "53 - 64",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
  },
  {
    id: 119,
    image: "https://cdn2.thedogapi.com/images/H1NIzlcV7_1280.jpg",
    name: "Giant Schnauzer",
    weight: "29 - 41",
    height: "60 - 70",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
  },
  {
    id: 120,
    image: "https://cdn2.thedogapi.com/images/H1oLMe94m_1280.jpg",
    name: "Glen of Imaal Terrier",
    weight: "15 - 18",
    height: "32 - 36",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Spirited, Agile, Loyal, Gentle, Active, Courageous",
  },
  {
    id: 121,
    image: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ_1280.jpg",
    name: "Golden Retriever",
    weight: "25 - 34",
    height: "55 - 61",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
  },
  {
    id: 123,
    image: "https://cdn2.thedogapi.com/images/SJ5vzx5NX_1280.jpg",
    name: "Gordon Setter",
    weight: "20 - 36",
    height: "58 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Fearless, Alert, Loyal, Confident, Gay, Eager",
  },
  {
    id: 124,
    image: "https://cdn2.thedogapi.com/images/B1Edfl9NX_1280.jpg",
    name: "Great Dane",
    weight: "50 - 86",
    height: "71 - 81",
    life_span: "7 - 10 years",
    belongToDb: false,
    temperament: "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
  },
  {
    id: 125,
    image: "https://cdn2.thedogapi.com/images/B12uzg9V7_1280.png",
    name: "Great Pyrenees",
    weight: "39 - 52",
    height: "64 - 81",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
  },
  {
    id: 127,
    image: "https://cdn2.thedogapi.com/images/ryNYMx94X_1280.jpg",
    name: "Greyhound",
    weight: "23 - 32",
    height: "69 - 76",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
  },
  {
    id: 128,
    image: "https://cdn2.thedogapi.com/images/ryoYGec4Q_1280.jpg",
    name: "Griffon Bruxellois",
    weight: "5",
    height: "23 - 28",
    life_span: "10 – 15 years",
    belongToDb: false,
    temperament:
      "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
  },
  {
    id: 129,
    image: "https://cdn2.thedogapi.com/images/B1IcfgqE7_1280.jpg",
    name: "Harrier",
    weight: "18 - 27",
    height: "46 - 56",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
  },
  {
    id: 130,
    image: "https://cdn2.thedogapi.com/images/rkXiGl9V7_1280.jpg",
    name: "Havanese",
    weight: "3 - 6",
    height: "22 - 29",
    life_span: "14 - 15 years",
    belongToDb: false,
    temperament:
      "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
  },
  {
    id: 134,
    image: "https://cdn2.thedogapi.com/images/S1osGeqVm_1280.jpg",
    name: "Irish Setter",
    weight: "16 - 32",
    height: "61 - 69",
    life_span: "10 - 11 years",
    belongToDb: false,
    temperament:
      "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
  },
  {
    id: 135,
    image: "https://cdn2.thedogapi.com/images/By-hGecVX_1280.jpg",
    name: "Irish Terrier",
    weight: "11 - 12",
    height: "46",
    life_span: "12 - 16 years",
    belongToDb: false,
    temperament:
      "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
  },
  {
    id: 137,
    image: "https://cdn2.thedogapi.com/images/Hyd2zgcEX_1280.jpg",
    name: "Irish Wolfhound",
    weight: "48 - 82",
    height: "76 - 89",
    life_span: "6 - 8 years",
    belongToDb: false,
    temperament:
      "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
  },
  {
    id: 138,
    image: "https://cdn2.thedogapi.com/images/SJAnzg9NX_1280.jpg",
    name: "Italian Greyhound",
    weight: "3 - 7",
    height: "33 - 38",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
  },
  {
    id: 140,
    image: "https://cdn2.thedogapi.com/images/r1H6feqEm_1280.jpg",
    name: "Japanese Chin",
    weight: "2 - 4",
    height: "20 - 28",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
  },
  {
    id: 141,
    image: "https://cdn2.thedogapi.com/images/HksaMxqNX_1280.jpg",
    name: "Japanese Spitz",
    weight: "7 - 9",
    height: "30 - 38",
    life_span: "10 – 16 years",
    belongToDb: false,
    temperament:
      "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
  },
  {
    id: 142,
    image: "https://cdn2.thedogapi.com/images/S1GAGg9Vm_1280.jpg",
    name: "Keeshond",
    weight: "16 - 20",
    height: "43 - 46",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Agile, Obedient, Playful, Quick, Sturdy, Bright",
  },
  {
    id: 144,
    image: "https://cdn2.thedogapi.com/images/Bko0fl547_1280.jpg",
    name: "Komondor",
    weight: "36 - 45",
    height: "65 - 70",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Steady, Fearless, Affectionate, Independent, Gentle, Calm",
  },
  {
    id: 145,
    image: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
    name: "Kooikerhondje",
    weight: "9 - 14",
    height: "36 - 41",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Benevolent, Agile, Alert, Intelligent, Active, Territorial",
  },
  {
    id: 147,
    image: "https://cdn2.thedogapi.com/images/BykZ7ecVX_1280.jpg",
    name: "Kuvasz",
    weight: "32 - 52",
    height: "66 - 76",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament:
      "Clownish, Loyal, Patient, Independent, Intelligent, Protective",
  },
  {
    id: 149,
    image: "https://cdn2.thedogapi.com/images/B1uW7l5VX_1280.jpg",
    name: "Labrador Retriever",
    weight: "25 - 36",
    height: "55 - 62",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered",
  },
  {
    id: 151,
    image: "https://cdn2.thedogapi.com/images/ryzzmgqE7_1280.jpg",
    name: "Lagotto Romagnolo",
    weight: "11 - 16",
    height: "41 - 48",
    life_span: "14 - 16 years",
    belongToDb: false,
    temperament: "Keen, Loyal, Companionable, Loving, Active, Trainable",
  },
  {
    id: 153,
    image: "https://cdn2.thedogapi.com/images/S1RGml5Em_1280.jpg",
    name: "Lancashire Heeler",
    weight: "3 - 6",
    height: "25 - 30",
    life_span: "12 – 15 years",
    belongToDb: false,
    temperament: "Clever, Friendly, Alert, Intelligent",
  },
  {
    id: 155,
    image: "https://cdn2.thedogapi.com/images/ByrmQlqVm_1280.jpg",
    name: "Leonberger",
    weight: "54 - 77",
    height: "65 - 80",
    life_span: "6 - 8 years",
    belongToDb: false,
    temperament: "Obedient, Fearless, Loyal, Companionable, Adaptable, Loving",
  },
  {
    id: 156,
    image: "https://cdn2.thedogapi.com/images/SJp7Qe5EX_1280.jpg",
    name: "Lhasa Apso",
    weight: "5 - 8",
    height: "25 - 28",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent",
  },
  {
    id: 161,
    image: "https://cdn2.thedogapi.com/images/B1SV7gqN7_1280.jpg",
    name: "Maltese",
    weight: "2 - 3",
    height: "20 - 25",
    life_span: "15 - 18 years",
    belongToDb: false,
    temperament:
      "Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active",
  },
  {
    id: 165,
    image: "https://cdn2.thedogapi.com/images/BkHHQgcN7_1280.jpg",
    name: "Miniature American Shepherd",
    weight: "9 - 18",
    height: "33 - 46",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Energetic, Loyal, Intelligent, Trainable",
  },
  {
    id: 167,
    image: "https://cdn2.thedogapi.com/images/Hy3H7g94X_1280.jpg",
    name: "Miniature Pinscher",
    weight: "4 - 5",
    height: "25 - 32",
    life_span: "15 years",
    belongToDb: false,
    temperament: "Clever, Outgoing, Friendly, Energetic, Responsive, Playful",
  },
  {
    id: 168,
    image: "https://cdn2.thedogapi.com/images/SJIUQl9NX_1280.jpg",
    name: "Miniature Schnauzer",
    weight: "5 - 9",
    height: "30 - 36",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Fearless, Friendly, Spirited, Alert, Obedient, Intelligent",
  },
  {
    id: 171,
    image: "https://cdn2.thedogapi.com/images/Sk4DXl54m_1280.jpg",
    name: "Newfoundland",
    weight: "45 - 68",
    height: "66 - 71",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament: "Sweet-Tempered, Gentle, Trainable",
  },
  {
    id: 172,
    image: "https://cdn2.thedogapi.com/images/B1ADQg94X_1280.jpg",
    name: "Norfolk Terrier",
    weight: "5 - 5",
    height: "23 - 25",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable",
  },
  {
    id: 176,
    image: "https://cdn2.thedogapi.com/images/BkgKXlqE7_1280.jpg",
    name: "Norwich Terrier",
    weight: "5 - 5",
    height: "25",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Hardy, Affectionate, Energetic, Sensitive, Intelligent",
  },
  {
    id: 177,
    image: "https://cdn2.thedogapi.com/images/SyYtQe5V7_1280.jpg",
    name: "Nova Scotia Duck Tolling Retriever",
    weight: "16 - 23",
    height: "43 - 53",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Outgoing, Alert, Patient, Intelligent, Loving",
  },
  {
    id: 178,
    image: "https://cdn2.thedogapi.com/images/HkZ57lq4m_1280.jpg",
    name: "Old English Sheepdog",
    weight: "27 - 45",
    height: "53",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving",
  },
  {
    id: 179,
    image: "https://cdn2.thedogapi.com/images/B1d5me547_1280.jpg",
    name: "Olde English Bulldogge",
    weight: "NaN",
    height: "38 - 48",
    life_span: "9 – 14 years",
    belongToDb: false,
    temperament: "Friendly, Alert, Confident, Loving, Courageous, Strong",
  },
  {
    id: 181,
    image: "https://cdn2.thedogapi.com/images/SkJj7e547_1280.jpg",
    name: "Papillon",
    weight: "1 - 5",
    height: "20 - 28",
    life_span: "13 - 17 years",
    belongToDb: false,
    temperament: "Hardy, Friendly, Energetic, Alert, Intelligent, Happy",
  },
  {
    id: 183,
    image: "https://cdn2.thedogapi.com/images/ByIiml9Nm_1280.jpg",
    name: "Pekingese",
    weight: "6",
    height: "15 - 23",
    life_span: "14 - 18 years",
    belongToDb: false,
    temperament:
      "Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent",
  },
  {
    id: 184,
    image: "https://cdn2.thedogapi.com/images/rJ6iQeqEm_1280.jpg",
    name: "Pembroke Welsh Corgi",
    weight: "11 - 14",
    height: "25 - 30",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Tenacious, Outgoing, Friendly, Bold, Playful, Protective",
  },
  {
    id: 185,
    image: "https://cdn2.thedogapi.com/images/S1V3Qeq4X_1280.jpg",
    name: "Perro de Presa Canario",
    weight: "40 - 50",
    height: "56 - 65",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Strong Willed, Suspicious, Gentle, Dominant, Calm",
  },
  {
    id: 188,
    image: "https://cdn2.thedogapi.com/images/Byz6mgqEQ_1280.jpg",
    name: "Pharaoh Hound",
    weight: "18 - 27",
    height: "53 - 64",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Affectionate, Sociable, Playful, Intelligent, Active, Trainable",
  },
  {
    id: 189,
    image: "https://cdn2.thedogapi.com/images/B1i67l5VQ_1280.jpg",
    name: "Plott",
    weight: "18 - 27",
    height: "51 - 64",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Bold, Alert, Loyal, Intelligent",
  },
  {
    id: 193,
    image: "https://cdn2.thedogapi.com/images/HJd0XecNX_1280.jpg",
    name: "Pomeranian",
    weight: "1 - 3",
    height: "20 - 30",
    life_span: "15 years",
    belongToDb: false,
    temperament:
      "Extroverted, Friendly, Sociable, Playful, Intelligent, Active",
  },
  {
    id: 196,
    image: "https://cdn2.thedogapi.com/images/Hkxk4ecVX_1280.jpg",
    name: "Poodle (Miniature)",
    weight: "7 - 8",
    height: "28 - 38",
    life_span: "12 – 15 years",
    belongToDb: false,
  },
  {
    id: 197,
    image: "https://cdn2.thedogapi.com/images/rJFJVxc4m_1280.jpg",
    name: "Poodle (Toy)",
    weight: "3 - 4",
    height: "23 - 28",
    life_span: "18 years",
    belongToDb: false,
  },
  {
    id: 201,
    image: "https://cdn2.thedogapi.com/images/HyJvcl9N7_1280.jpg",
    name: "Pug",
    weight: "6 - 8",
    height: "25 - 30",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive",
  },
  {
    id: 204,
    image: "https://cdn2.thedogapi.com/images/ryPgVl5N7_1280.jpg",
    name: "Puli",
    weight: "11 - 16",
    height: "41 - 43",
    life_span: "12 - 16 Years years",
    belongToDb: false,
    temperament: "Energetic, Agile, Loyal, Obedient, Intelligent, Faithful",
  },
  {
    id: 205,
    image: "https://cdn2.thedogapi.com/images/SyRe4xcN7_1280.jpg",
    name: "Pumi",
    weight: "8 - 15",
    height: "38 - 47",
    life_span: "13 - 15 years",
    belongToDb: false,
    temperament: "Lively, Reserved, Intelligent, Active, Protective, Vocal",
  },
  {
    id: 207,
    image: "https://cdn2.thedogapi.com/images/HkXWNl9E7_1280.jpg",
    name: "Rat Terrier",
    weight: "4 - 11",
    height: "25 - 33",
    life_span: "12 - 18 years",
    belongToDb: false,
    temperament:
      "Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving",
  },
  {
    id: 208,
    image: "https://cdn2.thedogapi.com/images/HJMzEl5N7_1280.jpg",
    name: "Redbone Coonhound",
    weight: "20 - 36",
    height: "53 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Affectionate, Energetic, Independent, Companionable, Familial, Unflappable",
  },
  {
    id: 209,
    image: "https://cdn2.thedogapi.com/images/By9zNgqE7_1280.jpg",
    name: "Rhodesian Ridgeback",
    weight: "34 - 36",
    height: "61 - 69",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent",
  },
  {
    id: 210,
    image: "https://cdn2.thedogapi.com/images/r1xXEgcNX_1280.jpg",
    name: "Rottweiler",
    weight: "34 - 50",
    height: "56 - 69",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament:
      "Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous",
  },
  {
    id: 211,
    image: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q_1280.jpg",
    name: "Russian Toy",
    weight: "1 - 3",
    height: "19 - 27",
    life_span: "10 - 12 years",
    belongToDb: false,
  },
  {
    id: 212,
    image: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
    name: "Saint Bernard",
    weight: "59 - 82",
    height: "65 - 70",
    life_span: "7 - 10 years",
    belongToDb: false,
    temperament: "Friendly, Lively, Gentle, Watchful, Calm",
  },
  {
    id: 213,
    image: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
    name: "Saluki",
    weight: "16 - 29",
    height: "58 - 71",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Aloof, Reserved, Intelligent, Quiet",
  },
  {
    id: 214,
    image: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm_1280.jpg",
    name: "Samoyed",
    weight: "23 - 27",
    height: "48 - 60",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Stubborn, Friendly, Sociable, Lively, Alert, Playful",
  },
  {
    id: 216,
    image: "https://cdn2.thedogapi.com/images/SyBvVgc47_1280.jpg",
    name: "Schipperke",
    weight: "5 - 7",
    height: "25 - 33",
    life_span: "13 - 15 years",
    belongToDb: false,
    temperament: "Fearless, Agile, Curious, Independent, Confident, Faithful",
  },
  {
    id: 218,
    image: "https://cdn2.thedogapi.com/images/SkNjqx9NQ_1280.jpg",
    name: "Scottish Deerhound",
    weight: "32 - 59",
    height: "71 - 81",
    life_span: "8 - 10 years",
    belongToDb: false,
    temperament: "Docile, Friendly, Dignified, Gentle",
  },
  {
    id: 219,
    image: "https://cdn2.thedogapi.com/images/Bklnce5NX_1280.jpg",
    name: "Scottish Terrier",
    weight: "8 - 10",
    height: "25",
    life_span: "11 - 13 years",
    belongToDb: false,
    temperament: "Feisty, Alert, Independent, Playful, Quick, Self-assured",
  },
  {
    id: 221,
    image: "https://cdn2.thedogapi.com/images/rJa29l9E7_1280.jpg",
    name: "Shetland Sheepdog",
    weight: "14",
    height: "33 - 41",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong",
  },
  {
    id: 222,
    image: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
    name: "Shiba Inu",
    weight: "8 - 10",
    height: "34 - 42",
    life_span: "12 - 16 years",
    belongToDb: false,
    temperament: "Charming, Fearless, Keen, Alert, Confident, Faithful",
  },
  {
    id: 223,
    image: "https://cdn2.thedogapi.com/images/BkrJjgcV7_1280.jpg",
    name: "Shih Tzu",
    weight: "4 - 7",
    height: "20 - 28",
    life_span: "10 - 18 years",
    belongToDb: false,
    temperament:
      "Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous",
  },
  {
    id: 225,
    image: "https://cdn2.thedogapi.com/images/SJJxjecEX_1280.jpg",
    name: "Shiloh Shepherd",
    weight: "54 - 64",
    height: "66 - 76",
    life_span: "9 – 14 years",
    belongToDb: false,
    temperament: "Outgoing, Loyal, Companionable, Gentle, Loving, Trainable",
  },
  {
    id: 226,
    image: "https://cdn2.thedogapi.com/images/S17ZilqNm_1280.jpg",
    name: "Siberian Husky",
    weight: "16 - 27",
    height: "51 - 60",
    life_span: "12 years",
    belongToDb: false,
    temperament: "Outgoing, Friendly, Alert, Gentle, Intelligent",
  },
  {
    id: 228,
    image: "https://cdn2.thedogapi.com/images/ByzGsl5Nm_1280.jpg",
    name: "Silky Terrier",
    weight: "4 - 5",
    height: "23 - 25",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Responsive, Inquisitive, Alert, Quick, Joyful",
  },
  {
    id: 232,
    image: "https://cdn2.thedogapi.com/images/Syszjx9Em_1280.jpg",
    name: "Smooth Fox Terrier",
    weight: "NaN - 8",
    height: "39",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Fearless, Affectionate, Alert, Playful, Intelligent, Active",
  },
  {
    id: 233,
    image: "https://cdn2.thedogapi.com/images/HJHmix5NQ_1280.jpg",
    name: "Soft Coated Wheaten Terrier",
    weight: "14 - 18",
    height: "41 - 46",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful",
  },
  {
    id: 235,
    image: "https://cdn2.thedogapi.com/images/HJf4jl9VX_1280.jpg",
    name: "Spanish Water Dog",
    weight: "14 - 23",
    height: "41 - 51",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent",
  },
  {
    id: 236,
    image: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm_1280.jpg",
    name: "Spinone Italiano",
    weight: "28 - 39",
    height: "57 - 70",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament: "Docile, Friendly, Affectionate, Loyal, Patient, Gentle",
  },
  {
    id: 238,
    image: "https://cdn2.thedogapi.com/images/H1zSie9V7_1280.jpg",
    name: "Staffordshire Bull Terrier",
    weight: "11 - 17",
    height: "36 - 41",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous",
  },
  {
    id: 239,
    image: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
    name: "Standard Schnauzer",
    weight: "14 - 23",
    height: "44 - 50",
    life_span: "13 - 15 years",
    belongToDb: false,
    temperament:
      "Trainable, Good-natured, Devoted, Lively, Playful, Intelligent",
  },
  {
    id: 242,
    image: "https://cdn2.thedogapi.com/images/HJ-Dix94Q_1280.jpg",
    name: "Swedish Vallhund",
    weight: "9 - 14",
    height: "29 - 34",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Fearless, Friendly, Energetic, Alert, Intelligent, Watchful",
  },
  {
    id: 243,
    image: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
    name: "Thai Ridgeback",
    weight: "16 - 25",
    height: "51 - 61",
    life_span: "10 - 12 years",
    belongToDb: false,
    temperament:
      "Protective, Loyal, Independent, Intelligent, Loving, Familial",
  },
  {
    id: 244,
    image: "https://cdn2.thedogapi.com/images/SkM9sec47_1280.jpg",
    name: "Tibetan Mastiff",
    weight: "39 - 64",
    height: "61 - 66",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament:
      "Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective",
  },
  {
    id: 245,
    image: "https://cdn2.thedogapi.com/images/Hyjcol947_1280.jpg",
    name: "Tibetan Spaniel",
    weight: "4 - 7",
    height: "25",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy",
  },
  {
    id: 246,
    image: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
    name: "Tibetan Terrier",
    weight: "9 - 11",
    height: "36 - 43",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive",
  },
  {
    id: 248,
    image: "https://cdn2.thedogapi.com/images/B17ase9V7_1280.jpg",
    name: "Toy Fox Terrier",
    weight: "2 - 4",
    height: "20 - 28",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Spirited, Alert, Loyal, Playful, Intelligent",
  },
  {
    id: 250,
    image: "https://cdn2.thedogapi.com/images/SkRpsgc47_1280.jpg",
    name: "Treeing Walker Coonhound",
    weight: "20 - 36",
    height: "51 - 69",
    life_span: "10 - 13 years",
    belongToDb: false,
    temperament:
      "Clever, Affectionate, Confident, Intelligent, Loving, Trainable",
  },
  {
    id: 251,
    image: "https://cdn2.thedogapi.com/images/r1o0jx9Em_1280.jpg",
    name: "Vizsla",
    weight: "23 - 29",
    height: "53 - 61",
    life_span: "10 - 14 years",
    belongToDb: false,
    temperament: "Affectionate, Energetic, Loyal, Gentle, Quiet",
  },
  {
    id: 253,
    image: "https://cdn2.thedogapi.com/images/SyU12l9V7_1280.jpg",
    name: "Weimaraner",
    weight: "25 - 41",
    height: "58 - 69",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament:
      "Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast",
  },
  {
    id: 254,
    image: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm_1280.jpg",
    name: "Welsh Springer Spaniel",
    weight: "16 - 25",
    height: "43 - 48",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Stubborn, Friendly, Affectionate, Loyal, Playful, Active",
  },
  {
    id: 256,
    image: "https://cdn2.thedogapi.com/images/Bkdx2g5Em_1280.jpg",
    name: "West Highland White Terrier",
    weight: "7 - 10",
    height: "25 - 28",
    life_span: "15 - 20 years",
    belongToDb: false,
    temperament: "Hardy, Friendly, Alert, Independent, Gay, Active, Courageous",
  },
  {
    id: 257,
    image: "https://cdn2.thedogapi.com/images/Hyv-ne94m_1280.jpg",
    name: "Whippet",
    weight: "11 - 16",
    height: "46 - 56",
    life_span: "12 - 15 years",
    belongToDb: false,
    temperament: "Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet",
  },
  {
    id: 258,
    image: "https://cdn2.thedogapi.com/images/r14M3e9E7_1280.jpg",
    name: "White Shepherd",
    weight: "27 - 39",
    height: "56 - 64",
    life_span: "12 – 14 years",
    belongToDb: false,
    temperament:
      "Self-confidence, Aloof, Fearless, Alert, Companionable, Eager",
  },
  {
    id: 259,
    image: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ_1280.jpg",
    name: "Wire Fox Terrier",
    weight: "7 - 9",
    height: "33 - 41",
    life_span: "13 – 14 years",
    belongToDb: false,
    temperament: "Fearless, Friendly, Bold, Keen, Alert, Quick",
  },
  {
    id: 260,
    image: "https://cdn2.thedogapi.com/images/Bkam2l9Vm_1280.jpg",
    name: "Wirehaired Pointing Griffon",
    weight: "20 - 32",
    height: "51 - 61",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament: "Loyal, Gentle, Vigilant, Trainable, Proud",
  },
  {
    id: 261,
    image: "https://cdn2.thedogapi.com/images/r1I4hl5Em_1280.jpg",
    name: "Wirehaired Vizsla",
    weight: "20 - 29",
    height: "55 - 64",
    life_span: "12 - 14 years",
    belongToDb: false,
  },
  {
    id: 262,
    image: "https://cdn2.thedogapi.com/images/HkNS3gqEm_1280.jpg",
    name: "Xoloitzcuintli",
    weight: "4 - 14",
    height: "25 - 58",
    life_span: "12 - 14 years",
    belongToDb: false,
    temperament:
      "Cheerful, Alert, Companionable, Intelligent, Protective, Calm",
  },
  {
    id: 264,
    image: "https://cdn2.thedogapi.com/images/B12BnxcVQ_1280.jpg",
    name: "Yorkshire Terrier",
    weight: "2 - 3",
    height: "20 - 23",
    life_span: "12 - 16 years",
    belongToDb: false,
    temperament: "Bold, Independent, Confident, Intelligent, Courageous",
  },
];

module.exports = savedInfo;

//First time, i take all the dogs info from this axios:

// require("dotenv").config();
// const { API_KEY } = process.env;
// const axios = require("axios");
// const URL = "https://api.thedogapi.com/v1/breeds";
// const imageURL = "https://api.thedogapi.com/v1/images";

// const getDogData = async () => {

//   const response = await axios.get(URL, { headers: { "x-api-key": API_KEY} });
//   const dogs = response.data;

//   const mappedDogs = await Promise.all(
//     dogs.map(async (dog) => {
//       const imageResponse = await axios.get(`${imageURL}/${dog.reference_image_id}`, { headers: {"x-api-key": API_KEY} } );
//       const image = imageResponse.data.url;

//       return {
//         id: dog.id,
//         image: image,
//         name: dog.name,
//         weight: dog.weight.metric,
//         height: dog.height.metric,
//         life_span: dog.life_span,
//         belongToDb: false,
//         temperament: dog.temperament,
//       };
//     })
//   );

//   if (!mappedDogs.length) throw Error("Info cant be properly obtained.");
//   return mappedDogs;
// };

// module.exports = getDogData;
